set tablespaceoid to MyDatabaseTableSpace if it's not OidIsValid
greenplum-db/diskquota pull request #133
Opened 2022-02-08 11:14 UTC by liuxueyang

Because we need the real tablespace id to get table size or add it to blackmap.

2022-02-15 10:07 UTC, higuoxing reviewed
Some comments from myself. Feel free to ignore any of them if I'm wrong :-)

2022-02-15 10:07 UTC, higuoxing commented on tests/regress/sql/test_default_tablespace.sql
> +-- start_ignore
It would be great to check the output of this query to show that the quota is set correctly.

2022-02-15 10:07 UTC, higuoxing commented on tests/regress/sql/test_default_tablespace.sql
> +SELECT diskquota.enable_hardlimit();
Does soft-limit have the same issue? If so, we'd better add tests for soft-limit as well :-)

2022-02-16 06:36 UTC, liuxueyang commented on tests/isolation2/sql/test_blackmap.sql
> +          AND reloid=REGEXP_REPLACE(given_name, '\D', '', 'g')::oid), 'g'), given_name);/*in func*/
`REGEXP_REPLACE` may return empty string which can't be converted to `oid` type.

2022-02-17 07:47 UTC, beeender reviewed
When you push the commit, please rewrite the commit message which should contain the below information: What is the problem? Why do we have an `InvalidOid` in these cases?

Follow this commit message template:
```
# Title: Summary, imperative, start upper case, don't end with a period
# No more than 50 chars. #### 50 chars is here: #

# Remember blank line between title and body.

# Body: Explain *what* and *why* (not *how*). Include task ID (tracker issue).
# Wrap at 72 chars. ################################## which is here: #

# At the end: Include Co-authored-by for all contributors.
# Include at least one empty line before it. Format:
# Co-authored-by: name <user@users.noreply.github.com>
#
# How to Write a Git Commit Message:
# https://chris.beams.io/posts/git-commit/
#
# 1.Separate subject from body with a blank line
# 2. Limit the subject line to 50 characters
# 3. Capitalize the subject line
# 4. Do not end the subject line with a period
# 5. Use the imperative mood in the subject line
# 6. Wrap the body at 72 characters
# 7. Use the body to explain what and why vs. how
```

2022-02-17 07:47 UTC, beeender commented on quotamodel.c
> +					tablespaceoid = entry->keys[1] == InvalidOid ? MyDatabaseTableSpace : entry->keys[1];
why do we need this? I think the invalid oid has been fixed already when adding the entry to the map?

Will it be clear if we only do check & fix in `update_limit_for_quota()` & `update_size_for_quota`? So it is clearly than any table_spaces we recorded in our data structure will be a valid one.

2022-02-17 07:47 UTC, beeender commented on tests/regress/sql/test_default_tablespace.sql
> +-- start_ignore
@liuxueyang comments?

2022-02-17 09:36 UTC, liuxueyang commented on tests/regress/sql/test_default_tablespace.sql
> +-- start_ignore
Already removed the ignore. It will check and show blackmap in the output now.

2022-02-17 10:43 UTC, xuebinsu reviewed
LGTM overall. Please re-trigger CI.

2022-02-17 10:43 UTC, xuebinsu commented on quotamodel.c
> +					tablespaceoid = entry->keys[1] == InvalidOid ? MyDatabaseTableSpace : entry->keys[1];
I agree. This is probably not needed.

2022-02-17 10:43 UTC, xuebinsu commented on tests/regress/expected/test_default_tablespace.out
> + role1   | custom_tablespace | ROLE_TABLESPACE_QUOTA
That's right!

2022-02-18 03:33 UTC, xuebinsu commented on tests/regress/sql/test_default_tablespace.sql
> +SELECT diskquota.wait_for_worker_new_epoch();
Why here? Should wait only when status of Diskquota is changed, e.g., after setting quota.

2022-02-21 10:15 UTC, xuebinsu approved these changes
Congratulations!

2022-02-22 00:28 UTC, xuebinsu requested changes
Per PR #146 , please add DISTRIBUTED BY for each CREATE TABLE.

2022-02-22 00:28 UTC, xuebinsu commented on tests/regress/sql/test_default_tablespace.sql
> +CREATE TABLE t_in_custom_tablespace AS SELECT generate_series(1, 50000000);
```suggestion
CREATE TABLE t_in_custom_tablespace (i) AS SELECT generate_series(1, 50000000) DISTRIBUTED BY (i);
```

2022-02-22 00:28 UTC, xuebinsu commented on tests/regress/sql/test_default_tablespace.sql
> +CREATE TABLE t (i int);
```suggestion
CREATE TABLE t (i int) DISTRIBUTED BY (i);
```

2022-02-22 00:28 UTC, xuebinsu commented on tests/regress/sql/test_default_tablespace.sql
> +CREATE TABLE t (i int);
```suggestion
CREATE TABLE t (i int) DISTRIBUTED BY (i);
```

2022-02-22 00:28 UTC, xuebinsu commented on tests/regress/sql/test_default_tablespace.sql
> +CREATE TABLE t_in_custom_tablespace AS SELECT generate_series(1, 100);
```suggestion
CREATE TABLE t_in_custom_tablespace (i) AS SELECT generate_series(1, 100) DISTRIBUTED BY (i);
```

2022-02-22 03:48 UTC, xuebinsu requested changes
Some code can be simplified. Please re-check

2022-02-22 03:48 UTC, xuebinsu commented on diskquota_utility.c
> +		rel->rd_node.spcNode = MyDatabaseTableSpace;
How can `spcNode` be invalid? It is set when `relation_open()`
```C
static void
RelationInitPhysicalAddr(Relation relation)
{
    if (relation->rd_rel->reltablespace)
        relation->rd_node.spcNode = relation->rd_rel->reltablespace;
    else
        relation->rd_node.spcNode = MyDatabaseTableSpace;
```

2022-02-22 03:48 UTC, xuebinsu commented on gp_activetable.c
> +	item.tablespaceoid = OidIsValid(relFileNode->node.spcNode) ? relFileNode->node.spcNode : MyDatabaseTableSpace;
This also should not be invalid.

2022-02-22 03:48 UTC, xuebinsu commented on quotamodel.c
> +						(type == NAMESPACE_TABLESPACE_QUOTA) || (type == ROLE_TABLESPACE_QUOTA) ? entry->keys[1] : InvalidOid;
Setting tablespace to invalid is probably not needed.

2022-02-22 03:48 UTC, xuebinsu commented on quotamodel.c
> +				reltablespace = MyDatabaseTableSpace;
1st access to `pg_class`: for refreshing quota

2022-02-22 03:48 UTC, xuebinsu commented on quotamodel.c
> +			*tablespaceoid = MyDatabaseTableSpace;
2nd access to `pg_class`: for soft limit check

2022-02-22 03:48 UTC, xuebinsu commented on quotamodel.c
> +			keyitem.tablespaceoid = MyDatabaseTableSpace;
This is probably not needed if `tablespaceoid` is not set to invaild when checking quota.

2022-02-22 03:48 UTC, xuebinsu commented on quotamodel.c
> +												form->reltablespace : MyDatabaseTableSpace;
3rd access to `pg_class`: dispatching blackmap for the main table

2022-02-22 03:48 UTC, xuebinsu commented on quotamodel.c
> +								curr_form->reltablespace : MyDatabaseTableSpace;
4th access to `pg_class`: dispatching blackmap for the auxilary tables

2022-02-22 03:48 UTC, xuebinsu commented on relation_cache.c
> +							  classForm->reltablespace : MyDatabaseTableSpace;
5th access to `pg_class`: calculating table size

2022-02-22 03:48 UTC, xuebinsu commented on relation_cache.c
> +										 classForm->reltablespace : MyDatabaseTableSpace;
Maybe we can remove this by removing `get_relation_entry()` in `calculate_table_size()`.

2022-02-23 03:54 UTC, beeender commented on quotamodel.c
> +						(type == NAMESPACE_TABLESPACE_QUOTA) || (type == ROLE_TABLESPACE_QUOTA) ? entry->keys[1] : InvalidOid;
@higuoxing Do you remember why do we need this? Didn't really get the comments :smile:

2022-02-23 04:04 UTC, xuebinsu commented on quotamodel.c
> +						(type == NAMESPACE_TABLESPACE_QUOTA) || (type == ROLE_TABLESPACE_QUOTA) ? entry->keys[1] : InvalidOid;
Probably because it is not used in those two cases.

2022-02-23 09:23 UTC, higuoxing commented on quotamodel.c
> +						(type == NAMESPACE_TABLESPACE_QUOTA) || (type == ROLE_TABLESPACE_QUOTA) ? entry->keys[1] : InvalidOid;
Yes, Xuebin's explanation is correct.

2022-02-23 10:12 UTC, beeender commented on quotamodel.c
> +			keyitem.tablespaceoid = MyDatabaseTableSpace;
we need to check if the keyitem is a hash entry, if it is, we cannot change it.
Actually it should be already checked before we add it to the cache.

2022-02-23 10:29 UTC, xuebinsu commented on quotamodel.c
> +			keyitem.tablespaceoid = MyDatabaseTableSpace;
Agree. We should never modify the key to the `HTAB`.

2022-02-24 14:10 UTC, Sasasu submitted a review, later dismissed

2022-02-24 14:12 UTC, Sasasu commented on tests/regress/sql/test_default_tablespace.sql
> +\! gpconfig -c "diskquota.hard_limit" -v "off" > /dev/null
👀

2022-02-25 00:57 UTC, xuebinsu submitted a review, later dismissed

2022-02-25 01:45 UTC, beeender submitted a review, later dismissed

2022-02-25 01:53 UTC, xuebinsu submitted a review, later dismissed

2022-02-25 02:03 UTC, Sasasu approved these changes

2022-02-25 07:38 UTC, beeender approved these changes

2022-02-25 08:20 UTC, Sasasu approved these changes

2022-02-25 08:31 UTC, merged