Minimize the risk of stale relfilenodes
greenplum-db/diskquota pull request #217
Opened 2022-04-25 09:57 UTC by xuebinsu

Since we do NOT take any lock when accessing info of a relation,
cache invalidation messages may not be delievered in time each time
we SeearchSysCache() for relfilenode. As a result, the relfilenode may
be stale and the table size may be incorrect.

This patch fixes this issue by

- Checking for invalidation messages each time before
SearchSysCache().
- Not removing a relation from active table map if the relfilenode
is stale.

Besides, since we do not remove the relfilenode if it maps to no
valid relation oid, we need remove those dangling relfilenodes
when unlink() to avoid memory leak.

2022-04-25 10:46 UTC, Sasasu approved these changes

2022-04-26 04:50 UTC, Sasasu requested changes

2022-04-26 04:50 UTC, Sasasu commented on gp_activetable.c
> +		ereport(WARNING,
remember change this to DEBUG level

2022-04-26 07:03 UTC, Sasasu approved these changes
the double negative in `is_relfilenode_stale()` is not clear, but I think is fine.

2022-04-26 07:17 UTC, beeender commented on diskquota.c
> +		EnableCatchupInterrupt();
```
void
procsignal_sigusr1_handler(SIGNAL_ARGS)
{
	int			save_errno = errno;

	if (CheckProcSignal(PROCSIG_CATCHUP_INTERRUPT))
		HandleCatchupInterrupt();
```

The catchup interrupt is triggered by `SIGUSR1`

```
void
EnableCatchupInterrupt(void)
{
	for (;;)
	{
		catchupInterruptEnabled = 1;
		if (!catchupInterruptOccurred)
			break;
		catchupInterruptEnabled = 0;
		if (catchupInterruptOccurred)
			ProcessCatchupEvent();
	}

}
```

`EnableCatchupInterrupt` only does the real work (`ProcessCatchupEvent()') when `catchupInterruptOccurred` is set. However, the only place set it is in `HandleCatchupInterrupt()` which is triggered by `SIGUSR1`.

The problem is, we overwrite the `SIGUSR1` handler by `	pqsignal(SIGUSR1, disk_quota_sigusr1);` at the beginning of `xxx_main` function. This means, for diskquota laucher & bgworkers, the `HandleCatchupInterrupt()` has never been called. (unlike Autovacuum, see https://github.com/greenplum-db/gpdb/blob/6X_STABLE/src/backend/postmaster/autovacuum.c#L467 )

So, my doubt is, the `EnableCatchupInterrupt()` and `DisableCatchupInterrupt()` here DOES NOT really do anything.

I could be wrong, let me know if there are more details which I am no aware of.

2022-04-26 07:29 UTC, xuebinsu commented on diskquota.c
> +		EnableCatchupInterrupt();
Good point! Now I know why the worker never receive the catchup interrupt.

Any idea how we should fix this?

2022-04-26 09:04 UTC, beeender reviewed
Looks good!

2022-04-26 09:04 UTC, beeender commented on diskquota.c
> +		EnableCatchupInterrupt();
We don't quite need the update-to-date syscache on bgworker I think? This file change won't be needed to fix the problem.

2022-04-26 09:06 UTC, xuebinsu commented on gp_activetable.c
> +	AcceptInvalidationMessages();
I think so.

2022-04-26 09:16 UTC, xuebinsu commented on gp_activetable.c
> +	 * Since we do not remove the relfilenode if it maps to no valid
The description here is not quite correct. I will update it.

2022-04-27 02:45 UTC, xuebinsu commented on quotamodel.c
> +	if (tupdesc && (tupdesc->natts != NUM_QUOTA_CONFIG_ATTRS || ((tupdesc)->attrs[0])->atttypid != OIDOID ||
Revered.

2022-04-27 02:46 UTC, xuebinsu commented on gp_activetable.c
> +	 * Since we do not remove the relfilenode if it maps to no valid
Updated.

2022-04-27 02:47 UTC, xuebinsu commented on diskquota.c
> +		EnableCatchupInterrupt();
I think we need this handler. Maybe we can add this later. Added a TODO item.

2022-04-27 03:08 UTC, fanfuxiaoran commented on diskquota.c
> +		EnableCatchupInterrupt();
As we have called "AcceptInvalidationMessages" where we need to fetch the latest catalog info, there is no need to call the  EnableCatchupInterrupt to catch catchup event.

2022-04-27 03:14 UTC, xuebinsu commented on gp_activetable.c
>  		if (relOid != InvalidOid)
Tried that. This is not enough to reduce the error probability. We'd better do this for each `SearchSysCache()`.

2022-04-27 03:22 UTC, beeender commented on diskquota.c
> +		EnableCatchupInterrupt();
code without doing anything will be confusing. Plus `CheckProcSignal` is a private function, we cannot handle `PROCSIG_CATCHUP_INTERRUPT` only by design. We may need to investigate if all other signals are interested to us as well.

I kind of agree with Xiaoran that `AcceptInvalidationMessages` already does the job, we don't have to catch the signals anymore.

Information like the comments here should exist in the comment to describe the alternative way of handling the same issue. To keep the code short and clean.

2022-04-27 03:30 UTC, xuebinsu commented on diskquota.c
> +		EnableCatchupInterrupt();
OK. I will revert it.

2022-04-28 01:46 UTC, beeender reviewed
LGTM, Let's merge if @fanfuxiaoran is fine with this as well.

2022-04-28 01:46 UTC, beeender commented on diskquota.c
> +#include "storage/sinval.h"
remove this

2022-04-28 02:03 UTC, fanfuxiaoran approved these changes

2022-04-28 03:45 UTC, fanfuxiaoran commented on diskquota.c
> +		EnableCatchupInterrupt();
>EnableCatchupInterrupt()
The main thing it does is calling "ProcessCatchupEvent " to process catchup event and set  "catchupInterruptEnabled" to true.
  I think it should be called at the beginning of a transaction to process the catchup event,  then call the function "DisableCatchupInterrupt" to set "catchupInterruptEnabled" to be false to disable the signal handler to process the catchup event while the main process is doing something to avoid current issues.

2022-04-28 06:23 UTC, xuebinsu commented on diskquota.c
> +		EnableCatchupInterrupt();
Then maybe we should call `AcceptInvalidationMessages()` manually.

2022-04-29 03:30 UTC, merged