Fix test_primary_failure test case
greenplum-db/diskquota pull request #303
Opened 2023-02-09 09:45 UTC by fanfuxiaoran

add plpython_version variable in test sql.
On gpdb6, plpython_version is plpythonu, on gpdb7, it's plpython3u

2023-02-16 08:32 UTC, zhrt123 commented
Should we use the name `test_primary_failure.in.sql`, which is the same as `test_rejectmap.in.sql`?

2023-02-16 08:48 UTC, fanfuxiaoran commented
> Should we use the name `test_primary_failure.in.sql`, which is the same as `test_rejectmap.in.sql`?

personally, I prefer this way. @beeender , how about you?

2023-02-16 14:07 UTC, beeender commented on tests/regress/sql/test_primary_failure.sql
> +create or replace language :plpython_version;
Let's use the way we introduced in #304  , so we can save lines 1-7.

Let me know if you don't have time to do that, I can help.

2023-02-20 08:13 UTC, fanfuxiaoran commented on tests/regress/sql/test_primary_failure.sql
> +create or replace language :plpython_version;
Done

2023-02-20 09:25 UTC, beeender approved these changes

2023-02-20 09:27 UTC, beeender requested changes
Wait,
`diskquota_schedule7` should be deleted now. And the `EXPECTED_DIR_SUFFIX` in the `tests/CMakeLists.txt` can be removed as well.

2023-02-20 09:29 UTC, fanfuxiaoran commented
> Wait, `diskquota_schedule7` should be deleted now. And the `EXPECTED_DIR_SUFFIX` in the `tests/CMakeLists.txt` can be removed as well.

Ok, I'll fix it by the way.

2023-02-20 09:36 UTC, beeender approved these changes

2023-02-21 07:22 UTC, merged